packages:
  - packages/*
  # NOTE: packages/cli/binaries/* and packages/http-server/binaries/* are NOT workspace packages
  # They are published independently via npm publish in CI (see scripts/publish-platform-packages.ts)

ignoredBuiltDependencies:
  - core-js
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - better-sqlite3

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
