//! Render command — generate navigable SPECS.md index for git-native viewing
//!
//! Enables viewing specs directly in GitHub/GitLab/Bitbucket without running a server.

use leanspec_core::{SpecLoader, SpecStatus};
use std::error::Error;
use std::fs;
use std::path::Path;

pub fn run(specs_dir: &str, output: Option<&str>, output_format: &str) -> Result<(), Box<dyn Error>> {
    let loader = SpecLoader::new(specs_dir);
    let mut specs = loader.load_all()?;

    // Sort by spec number (ascending)
    specs.sort_by_key(|a| a.number());

    let mut md = String::new();

    // Header
    md.push_str("# Specs Index\n\n");
    md.push_str("> Auto-generated by `lean-spec render`. Do not edit manually.\n\n");

    // Summary counts
    let total = specs.len();
    let by_status = |s: SpecStatus| specs.iter().filter(|spec| spec.frontmatter.status == s).count();
    let draft = by_status(SpecStatus::Draft);
    let planned = by_status(SpecStatus::Planned);
    let in_progress = by_status(SpecStatus::InProgress);
    let complete = by_status(SpecStatus::Complete);
    let archived = by_status(SpecStatus::Archived);

    md.push_str(&format!(
        "**{}** specs — {} draft, {} planned, {} in progress, {} complete, {} archived\n\n",
        total, draft, planned, in_progress, complete, archived
    ));

    // Table header
    md.push_str("| # | Title | Status | Priority | Assignee |\n");
    md.push_str("|---|-------|--------|----------|----------|\n");

    for spec in &specs {
        let num = spec
            .number()
            .map(|n| format!("{:03}", n))
            .unwrap_or_else(|| "-".to_string());

        let title_link = format!(
            "[{}]({}/README.md)",
            spec.title.replace('|', "\\|"),
            spec.path
        );

        let status = format!(
            "{} {}",
            spec.frontmatter.status_emoji(),
            spec.frontmatter.status_label()
        );

        let priority = spec
            .frontmatter
            .priority
            .as_ref()
            .map(|p| format!("{}", p))
            .unwrap_or_else(|| "-".to_string());

        let assignee = spec
            .frontmatter
            .assignee
            .as_deref()
            .unwrap_or("-")
            .to_string();

        md.push_str(&format!(
            "| {} | {} | {} | {} | {} |\n",
            num, title_link, status, priority, assignee
        ));
    }

    // Write output
    let output_path = output.unwrap_or("SPECS.md");
    let output_path = Path::new(output_path);
    fs::write(output_path, &md)?;

    if output_format == "json" {
        let result = serde_json::json!({
            "output": output_path.to_string_lossy(),
            "specs_count": total,
        });
        println!("{}", serde_json::to_string_pretty(&result)?);
    } else {
        println!(
            "Generated {} with {} specs → {}",
            output_path.display(),
            total,
            output_path.display()
        );
    }

    Ok(())
}
